apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-dev
resources:
  - sparkapplication.yaml
configMapGenerator:
  - name: spark-pi-7-code
    files:
      - spark_pi_7.py
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: spark-pi-7
    app.kubernetes.io/part-of: gemius-spark
